USE [master]
GO

/****** Object:  Database [QuanLy_ThuVien]    Script Date: 7/15/2022 11:08:18 AM ******/
CREATE DATABASE [QuanLy_ThuVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLy_ThuVien', FILENAME = N'E:\LearnIT\HK6\HQTCSDL-T6-17h30\Test_nhaplieu\QuanLy_ThuVien.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLy_ThuVien_log', FILENAME = N'E:\LearnIT\HK6\HQTCSDL-T6-17h30\Test_nhaplieu\QuanLy_ThuVien_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLy_ThuVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLy_ThuVien] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QuanLy_ThuVien] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLy_ThuVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLy_ThuVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QuanLy_ThuVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLy_ThuVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QuanLy_ThuVien] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLy_ThuVien] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLy_ThuVien] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLy_ThuVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLy_ThuVien] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLy_ThuVien] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLy_ThuVien] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLy_ThuVien] SET  READ_WRITE 
GO

